# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cbc2f6442cbf1c398dc8f4461226eb5de7c20a113cf596f91acaa3079cb244890e2c1ad68e122deda6671a0f9ab0c2b417eeb0de887c27fc86c4e9125b0211c

test:
  secret_key_base: 6970762c08584cfc9d0cf84a278cffd9476d9e8649e87448374f38ce26e897d83560d54e38b1ea24ccf6e90f098d70bc343b9d22236d0446c1e35cce1529a942

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
