pub1 = PublishingHouse.find_or_create_by!(name: 'ABC Publisher', discount: 0.4)
pub2 = PublishingHouse.find_or_create_by!(name: 'Acme Publishing House', discount: 0.5)
pub3 = PublishingHouse.find_or_create_by!(name: 'Foobar Corporation', discount: 0.0)

author1 = Author.find_or_create_by!(name: 'James Jackson')
author2 = Author.find_or_create_by!(name: 'Roberta Rock')
author3 = Author.find_or_create_by!(name: 'Daniel Duck')
author4 = Author.find_or_create_by!(name: 'Amanda Djidjinski')
author5 = Author.find_or_create_by!(name: 'Zoe Zack')
author6 = Author.find_or_create_by!(name: 'Bill Burray')
author7 = Author.find_or_create_by!(name: 'Charlie Chuck')

book1 = Book.find_or_create_by!(title: 'The Great Escape', author: author7, publisher: pub1, price: 24.20)
book2 = Book.find_or_create_by!(title: 'Saving Myself', author: author6, publisher: pub1, price: 14.13)
book3 = Book.find_or_create_by!(title: 'The Killer Doctors', author: author5, publisher: pub1, price: 15.12)
book4 = Book.find_or_create_by!(title: 'Marianne', author: author4, publisher: pub1, price: 10.50)
book5 = Book.find_or_create_by!(title: 'On the Verge of Salvation', author: author4, publisher: pub2, price: 11.76)
book6 = Book.find_or_create_by!(title: 'Fields of L', author: author3, publisher: pub2, price: 27.87)
book7 = Book.find_or_create_by!(title: 'Waterfront', author: author2, publisher: pub2, price: 11.97)
book8 = Book.find_or_create_by!(title: 'Bored as Hell', author: author6, publisher: pub3, price: 10.96)
book9 = Book.find_or_create_by!(title: 'History of the Silk Road', author: author7, publisher: pub3, price: 8.10)
booka = Book.find_or_create_by!(title: 'Something for Later', author: author1, publisher: author1, price: 9.54)
bookb = Book.find_or_create_by!(title: 'What If', author: author3, publisher: author3, price: 13.32)
bookc = Book.find_or_create_by!(title: 'Lilly Reborn', author: author4, publisher: pub3, price: 16.43)
bookd = Book.find_or_create_by!(title: 'Anathema', author: author5, publisher: author5, price: 9.41)
booke = Book.find_or_create_by!(title: 'Best Of', author: author2, publisher: pub3, price: 12.24)
bookf = Book.find_or_create_by!(title: 'Anyway', author: author6, publisher: pub3, price: 19.99)