pub1 = PublishingHouse.create(name: "ABC Publisher", discount: 0.4)
pub2 = PublishingHouse.create(name: "Acme Publishing House", discount: 0.5)
pub3 = PublishingHouse.create(name: "Foobar Corporation", discount: 0.0)

author1 = Author.create(name: "James Jackson")
author2 = Author.create(name: "Roberta Rock")
author3 = Author.create(name: "Daniel Duck")
author4 = Author.create(name: "Amanda Djidjinski")
author5 = Author.create(name: "Zoe Zack")
author6 = Author.create(name: "Bill Burray")
author7 = Author.create(name: "Charlie Chuck")